/* =============================================
   zornavik.me — Product Registry
   Single source of truth for all product review pages.
   Product URLs: /products/<slug>
   Rendering is controlled entirely from this file + main.js helpers below.
   ============================================= */

const PRODUCT_REGISTRY = [
  {
    serial: 1,
    slug: "eureka-reacticlean-410-cordless-vacuum",
    title: "Eureka ReactiClean 410 Cordless Vacuum",
    brand: "Eureka",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 116.99,
    oldPrice: 129.99,
    rating: 4.2,
    reviewCount: 1190,
    badge: "Amazon's Choice",
    bestFor: "Best Overall Cordless",
    image: "/images/products/eureka-reacticlean-410-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/4yxo2H6",
    slugUrl: "/products/eureka-reacticlean-410-cordless-vacuum",
    quickSpecs: [["Suction Power", "20.3 kPa"], ["Battery Runtime", "Up to 50 min"], ["Weight", "5.5 lbs"], ["Filter", "5-Stage Washable HEPA"], ["Warranty", "2-Year Manufacturer"]],
    features: ["Detachable battery lets you hot-swap for extended runtime", "Converts to a handheld vacuum in seconds", "Digital display shows live battery percentage", "Tangle-resistant brush head reduces hair wrap", "Includes wall-mount storage dock"],
    pros: ["Lightweight and easy to maneuver around furniture", "Strong everyday suction on hardwood, rugs and pet hair", "Washable HEPA filter keeps running costs low"],
    cons: ["Battery drains quickly on the highest suction setting", "Doesn't stand upright on its own without the dock", "Recharge time runs 4–5 hours"],
    summary: "A well-balanced cordless stick vacuum that trades some max-power runtime for a genuinely lightweight, easy-to-empty design. An easy recommendation for apartments, pet owners and everyday hardwood or carpet cleanup.",
  },
  {
    serial: 2,
    slug: "timitrek-cordless-vacuum-cleaner",
    title: "Timitrek Cordless Vacuum Cleaner",
    brand: "Timitrek",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 109.99,
    oldPrice: null,
    rating: 4.7,
    reviewCount: 247,
    badge: null,
    bestFor: "Best Value Cordless",
    image: "/images/products/timitrek-cordless-vacuum-cleaner.webp",
    affiliateUrl: "https://amzn.to/4b5OddZ",
    slugUrl: "/products/timitrek-cordless-vacuum-cleaner",
    quickSpecs: [["Suction Power", "50 kPa"], ["Motor", "600W"], ["Battery Runtime", "Up to 60 min"], ["Filter", "HEPA"], ["Warranty", "2 Years"]],
    features: ["Self-standing design — no wall dock required", "3 selectable suction modes", "LED display with green floor headlights", "180° swivel floor head for tight corners", "Wall-mount storage dock included"],
    pros: ["Genuinely self-standing, no dock needed to store it", "Bright floor lights reveal hidden dust", "Strong suction relative to the price"],
    cons: ["Max suction mode burns through the battery in ~15 minutes", "No dedicated onboard accessory storage"],
    summary: "A budget-friendly, self-standing stick vacuum with an unusually strong 4.7-star average. Great for daily quick cleanups — just save the max mode for spot-cleaning.",
  },
  {
    serial: 3,
    slug: "amazon-basics-wet-dry-shop-vacuum",
    title: "Amazon Basics Wet/Dry Shop Vacuum",
    brand: "Amazon Basics",
    type: "Wet/Dry Shop Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: 62.45,
    oldPrice: null,
    rating: 4.4,
    reviewCount: 3241,
    badge: "Amazon's Choice",
    bestFor: "Best Shop Vacuum",
    image: "/images/products/amazon-basics-wet-dry-shop-vacuum.webp",
    affiliateUrl: "https://amzn.to/4fRPTKJ",
    slugUrl: "/products/amazon-basics-wet-dry-shop-vacuum",
    quickSpecs: [["Capacity", "4 Gallon"], ["Motor", "3 HP"], ["Cord Length", "8 ft"], ["Filter", "Cloth + Foam"], ["Power Source", "Corded, 120V"]],
    features: ["Wet & dry pickup with reusable cloth and foam filters", "Stainless-steel tank body", "Built-in blower function", "4 caster wheels for easy movement", "Onboard accessory storage"],
    pros: ["Compact size compared to full-size shop vacs", "Handles wet spills and dry debris equally well", "Wheeled, portable design"],
    cons: ["Power cord is fairly short at 8 ft", "Hose and extension wands feel a little flimsy", "Louder than a typical household vacuum"],
    summary: "A mid-size wet/dry shop vacuum that lands neatly between bulky industrial units and small handhelds — a strong fit for garages, workshops and vehicle detailing.",
  },
  {
    serial: 4,
    slug: "nuyupo-dhc100-cordless-vacuum",
    title: "NuYupo 10-in-1 Cordless Vacuum",
    brand: "NuYupo",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 79.99,
    oldPrice: null,
    rating: 4.4,
    reviewCount: 610,
    badge: null,
    bestFor: "Best Budget 10-in-1",
    image: "/images/products/nuyupo-dhc100-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/4wUf6d9",
    slugUrl: "/products/nuyupo-dhc100-cordless-vacuum",
    quickSpecs: [["Motor", "480W Brushless"], ["Battery Runtime", "Up to 45 min (Eco)"], ["Weight", "Under 5 lbs"], ["Filter", "6-Stage HEPA"], ["Dust Cup", "1.5 L"]],
    features: ["10-in-1 attachment kit, including a dryer-vent cleaner", "270° rotating anti-tangle brush", "LED touch-screen display", "Detachable rechargeable battery", "Extra HEPA filter set included in the box"],
    pros: ["Huge attachment kit for the price", "Lightweight and easy for daily use", "Spare filter included at no extra cost"],
    cons: ["Struggles on thick, high-pile carpet", "Newer listing, so long-term durability is still unproven"],
    summary: "A feature-packed budget cordless vacuum whose 10-in-1 accessory kit covers everything from dryer vents to car interiors — best suited to hard floors and light carpet.",
  },
  {
    serial: 5,
    slug: "eureka-neu10ae5-bagless-upright-vacuum",
    title: "Eureka NEU10AE5 Bagless Upright Vacuum",
    brand: "Eureka",
    type: "Corded Upright Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: 59.98,
    oldPrice: null,
    rating: 4.3,
    reviewCount: 39776,
    badge: "Amazon's Choice",
    bestFor: "Best Budget Upright",
    image: "/images/products/eureka-neu10ae5-bagless-upright-vacuum.webp",
    affiliateUrl: "https://amzn.to/3TiFZZU",
    slugUrl: "/products/eureka-neu10ae5-bagless-upright-vacuum",
    quickSpecs: [["Suction Power", "12 kPa"], ["Motor", "720W"], ["Weight", "7.7 lbs"], ["Cord Length", "25 ft"], ["Filter", "Washable Foam"]],
    features: ["10.5-inch cleaning width", "Large 1.7 L dust cup", "Includes crevice tool and dusting brush", "Performs well on hard floors and low-pile carpet", "No motorized brushroll"],
    pros: ["Very affordable and lightweight at 7.7 lbs", "Large dust cup means less frequent emptying", "Washable filter keeps ongoing costs low"],
    cons: ["No motorized brushroll, so it's weaker on thick plush carpet", "No HEPA filtration", "Runs fairly loud at around 82 dB"],
    summary: "One of the best-reviewed budget uprights on Amazon, with nearly 40,000 ratings backing it up — an easy, affordable pick for hard floors, low-pile carpet and everyday pet hair.",
  },
  {
    serial: 6,
    slug: "hfflh-cordless-vacuum-cleaner",
    title: "HFFLH Cordless Stick Vacuum",
    brand: "HFFLH",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 89.98,
    oldPrice: 149.99,
    rating: 4.7,
    reviewCount: 209,
    badge: "Prime Exclusive",
    bestFor: "Best Prime Deal",
    image: "/images/products/hfflh-cordless-vacuum-cleaner.webp",
    affiliateUrl: "https://amzn.to/4x4CQLV",
    slugUrl: "/products/hfflh-cordless-vacuum-cleaner",
    quickSpecs: [["Motor", "600W Brushless"], ["Suction Power", "50 kPa"], ["Battery Runtime", "Up to 65 min"], ["Filter", "HEPA"], ["Warranty", "3-Year"]],
    features: ["Self-standing design", "Touch-screen display", "Anti-tangle V-shaped brush", "Cleans car interiors and keyboards", "Converts to a handheld vacuum"],
    pros: ["Long 65-minute runtime for this class", "3-year warranty is well above average", "Excellent suction-to-price ratio"],
    cons: ["Manufacturer doesn't disclose exact weight", "Fewer long-term reviews than more established brands"],
    summary: "A strong-suction, long-runtime cordless vacuum backed by an unusually long 3-year warranty — frequently available at a steep discount through Prime pricing.",
  },
  {
    serial: 7,
    slug: "kttldrn-cordless-vacuum-cleaner",
    title: "KTTLDRN Cordless Vacuum Cleaner",
    brand: "KTTLDRN",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 99.99,
    oldPrice: null,
    rating: 4.0,
    reviewCount: 38,
    badge: null,
    bestFor: "Longest Runtime Pick",
    image: "/images/products/kttldrn-cordless-vacuum-cleaner.webp",
    affiliateUrl: "https://amzn.to/4x61hbP",
    slugUrl: "/products/kttldrn-cordless-vacuum-cleaner",
    quickSpecs: [["Motor", "650W Brushless"], ["Suction Power", "55 kPa"], ["Battery Runtime", "Up to 70 min"], ["Dust Cup", "1.8 L"], ["Filter", "HEPA"]],
    features: ["OLED display", "Self-standing design", "Anti-tangle brush head", "High 55 kPa rated suction", "1.8 L dust cup — larger than most cordless models"],
    pros: ["Longest advertised runtime in this roundup at 70 minutes", "Large dust cup means fewer stops to empty it", "High suction rating on paper"],
    cons: ["Small review sample size so far", "Full accessory list isn't clearly specified"],
    summary: "On paper, the longest-runtime and largest-capacity cordless vacuum in our lineup. Worth watching as more reviews come in, though it's currently a newer, less-proven listing.",
  },
  {
    serial: 8,
    slug: "slivamo-s10-cordless-vacuum",
    title: "Slivamo S10 Cordless Vacuum",
    brand: "Slivamo",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 99.98,
    oldPrice: 109.98,
    rating: 3.8,
    reviewCount: 75,
    badge: null,
    bestFor: "Budget Pick",
    image: "/images/products/slivamo-s10-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/4pJtMJU",
    slugUrl: "/products/slivamo-s10-cordless-vacuum",
    quickSpecs: [["Model", "S10"], ["Motor", "500W"], ["Suction Power", "40 kPa"], ["Battery Runtime", "Up to 45 min (Eco)"], ["Filter", "6-Layer HEPA"]],
    features: ["LED display", "6-layer sealed filtration system", "Includes extension wand and handheld unit", "Multiple cleaning attachments"],
    pros: ["6-layer filtration seals in fine dust", "Converts easily to a handheld unit", "Reasonable price point"],
    cons: ["Lowest average rating in this roundup", "Suction and runtime trail similarly priced competitors"],
    summary: "A budget cordless option with a solid filtration system, though its rating lags behind other vacuums at the same price — worth comparing against the Timitrek or NuYupo first.",
  },
  {
    serial: 9,
    slug: "vipsun-cordless-vacuum-cleaner",
    title: "VIPSUN Cordless Vacuum Cleaner",
    brand: "VIPSUN",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 79.99,
    oldPrice: 99.99,
    rating: 4.5,
    reviewCount: null,
    badge: "Amazon's Choice",
    bestFor: "Best for Dorms & Small Spaces",
    image: "/images/products/vipsun-cordless-vacuum-cleaner.webp",
    affiliateUrl: "https://amzn.to/4vMQUIZ",
    slugUrl: "/products/vipsun-cordless-vacuum-cleaner",
    quickSpecs: [["Suction Power", "40 kPa"], ["Battery Runtime", "Up to 50 min"], ["Filter", "Cotton Filter"], ["Design", "Self-Standing"], ["Weight", "Lightweight"]],
    features: ["Self-standing design", "LED screen", "Large-capacity dust cup", "Includes floor brush, crevice tool and 2-in-1 combo brush"],
    pros: ["Lightweight and easy to store upright", "Good suction for the price", "Amazon's Choice badge with a strong rating"],
    cons: ["Cotton filter (not HEPA) may need more frequent cleaning", "Dust cup capacity isn't officially listed"],
    summary: "A lightweight, self-standing cordless vacuum aimed squarely at dorms, apartments and small homes — simple to store and easy to live with day to day.",
  },
  {
    serial: 10,
    slug: "ixlion-cordless-vacuum-cleaner",
    title: "iXlion Cordless Vacuum Cleaner",
    brand: "iXlion",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 94.95,
    oldPrice: 129.89,
    rating: 4.2,
    reviewCount: null,
    badge: "Amazon's Choice",
    bestFor: "Best Dual-Filter Pick",
    image: "/images/products/ixlion-cordless-vacuum-cleaner.webp",
    affiliateUrl: "https://amzn.to/4pGlKkZ",
    slugUrl: "/products/ixlion-cordless-vacuum-cleaner",
    quickSpecs: [["Motor", "550W"], ["Suction Power", "45,000 Pa"], ["Battery Runtime", "Up to 55 min"], ["Weight", "6 lbs"], ["Filter", "Dual HEPA + Stainless Steel"]],
    features: ["Detachable battery", "LED headlight", "Anti-tangle brush", "Dual HEPA + stainless-steel filter stack", "Wall mount and an extra filter included"],
    pros: ["Dual-stage filtration is above average for the price", "Detachable battery makes swapping in a spare easy", "Ships with a spare filter"],
    cons: ["Max-mode battery life drops to around 20 minutes", "Slightly heavier than the lightest competitors at 6 lbs"],
    summary: "The dual HEPA + stainless-steel filter setup gives this iXlion model an edge in dust capture versus similarly priced cordless vacuums.",
  },
  {
    serial: 11,
    slug: "pinico-s7-cordless-vacuum",
    title: "PINICO S7 Cordless Vacuum",
    brand: "PINICO",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 119.99,
    oldPrice: 129.99,
    rating: 4.6,
    reviewCount: 11,
    badge: "New Arrival",
    bestFor: "Newest Release",
    image: "/images/products/pinico-s7-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/4vXf2Zn",
    slugUrl: "/products/pinico-s7-cordless-vacuum",
    quickSpecs: [["Model", "S7"], ["Motor", "550W Brushless"], ["Suction Power", "48 kPa"], ["Battery Runtime", "Up to 60 min (Eco)"], ["Filter", "HEPA"]],
    features: ["3 suction modes: Eco, Normal and Turbo", "Wall-mounted charging dock", "Works on marble and hard floors", "Includes user manual and multiple attachments"],
    pros: ["Strong early rating at 4.6/5", "Three clearly defined power modes", "Good runtime in Eco mode"],
    cons: ["Very new listing with only a handful of reviews so far", "Slightly heavier packaged weight at 7.9 lbs"],
    summary: "A newly listed cordless vacuum with an early 4.6-star average — promising, though it's worth watching for more reviews before it earns a top-tier recommendation.",
  },
  {
    serial: 12,
    slug: "levoit-lvac-200-cordless-vacuum",
    title: "Levoit LVAC-200 Cordless Vacuum",
    brand: "Levoit",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: null,
    oldPrice: null,
    rating: 4.2,
    reviewCount: 13880,
    badge: "Amazon's Choice",
    bestFor: "Best for Pet Hair (Anti-Tangle)",
    image: "/images/products/levoit-lvac-200-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/4vRmpBA",
    slugUrl: "/products/levoit-lvac-200-cordless-vacuum",
    quickSpecs: [["Model", "LVAC-200 Essential"], ["Battery Runtime", "Up to 50 min (Pet Tool)"], ["Filter", "5-Stage Foam"], ["Included", "Pet Tool, Dusting Brush, Wall Hook"], ["Color", "Arctic White"]],
    features: ["Anti-tangle design built specifically for pet hair", "2-in-1 pet tool and crevice tool", "Wall hook for storage", "5-stage filtration"],
    pros: ["Purpose-built anti-tangle brush for pet owners", "Nearly 14,000 ratings back up its reliability", "From a trusted air-quality brand"],
    cons: ["Turbo mode runtime is short at around 12 minutes", "Suction rating isn't disclosed by the manufacturer"],
    summary: "Levoit brings its air-quality expertise to a cordless vacuum built specifically to resist pet-hair tangles — one of the most-reviewed picks in this entire guide.",
  },
  {
    serial: 13,
    slug: "shark-navigator-lift-away-nv360",
    title: "Shark Navigator Lift-Away Deluxe (NV360)",
    brand: "Shark",
    type: "Corded Upright Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: null,
    oldPrice: null,
    rating: 4.4,
    reviewCount: 54257,
    badge: "Amazon's Choice",
    bestFor: "Best-Selling Upright",
    image: "/images/products/shark-navigator-lift-away-nv360.webp",
    affiliateUrl: "https://amzn.to/4fXusrC",
    slugUrl: "/products/shark-navigator-lift-away-nv360",
    quickSpecs: [["Model", "NV360"], ["Power Source", "Corded Electric"], ["Dust Cup", "0.9 qt"], ["Filter", "HEPA + Anti-Allergen Seal"], ["Included", "Upholstery + Crevice Tool"]],
    features: ["Lift-Away detachable canister for portable cleaning", "Swivel steering", "Anti-Allergen Complete Seal technology", "Washable HEPA filter"],
    pros: ["Over 54,000 ratings — one of the most trusted uprights on Amazon", "Lift-Away pod detaches for stairs and furniture", "Swivel steering handles tight corners easily"],
    cons: ["No cordless convenience", "Bagless bin needs regular emptying in larger homes"],
    summary: "The Shark Navigator Lift-Away is a long-running Amazon best-seller for good reason — reliable suction, versatile Lift-Away portability, and true HEPA filtration for allergy sufferers.",
  },
  {
    serial: 14,
    slug: "eureka-whirlwind-canister-vacuum",
    title: "Eureka WhirlWind Bagless Canister Vacuum",
    brand: "Eureka",
    type: "Corded Canister Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: null,
    oldPrice: null,
    rating: 4.3,
    reviewCount: 30394,
    badge: "Amazon's Choice",
    bestFor: "Best Canister Vacuum",
    image: "/images/products/eureka-whirlwind-canister-vacuum.webp",
    affiliateUrl: "https://amzn.to/3RgeXlr",
    slugUrl: "/products/eureka-whirlwind-canister-vacuum",
    quickSpecs: [["Model", "NEN110A"], ["Motor", "960W"], ["Weight", "8.15 lbs"], ["Dust Cup", "2.5 L"], ["Filter", "Washable Disk"]],
    features: ["Telescoping metal wand", "2-in-1 crevice tool / dusting brush", "Compact canister body", "Washable filter"],
    pros: ["Large 2.5 L dust cup means fewer empties", "Compact canister is easy to store", "Nearly 30,400 ratings at 4.3 stars"],
    cons: ["Corded only, no cordless convenience", "Fewer attachments than pricier models"],
    summary: "A budget-friendly bagless canister with a surprisingly large dust cup and a huge review base — solid for hard floors, stairs and upholstery.",
  },
  {
    serial: 15,
    slug: "eureka-powerspeed-upright-vacuum",
    title: "Eureka PowerSpeed Upright Vacuum",
    brand: "Eureka",
    type: "Corded Upright Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: 75.99,
    oldPrice: null,
    rating: 4.4,
    reviewCount: 17732,
    badge: "Amazon's Choice",
    bestFor: "Best Lightweight Upright",
    image: "/images/products/eureka-powerspeed-upright-vacuum.webp",
    affiliateUrl: "https://amzn.to/4fGpIp7",
    slugUrl: "/products/eureka-powerspeed-upright-vacuum",
    quickSpecs: [["Motor", "960W"], ["Weight", "11.5 lbs"], ["Dust Cup", "1.9 L"], ["Filter", "Foam"], ["Warranty", "2-Year Limited"]],
    features: ["Includes dusting brush, crevice tool and upholstery tool", "Stretch hose for extra reach", "Works on carpet, hard floors and shag rugs"],
    pros: ["Full accessory kit included at a budget price", "Backed by a 2-year limited warranty", "Nearly 17,700 positive ratings"],
    cons: ["Heavier than cordless stick alternatives at 11.5 lbs", "Foam filter isn't true HEPA"],
    summary: "A well-rounded, budget-priced corded upright with a genuinely useful accessory kit included — hard to beat for the price if cordless isn't a requirement.",
  },
  {
    serial: 16,
    slug: "bissell-cleanview-compact-3508",
    title: "Bissell CleanView Compact 3508",
    brand: "Bissell",
    type: "Corded Upright Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: 89.97,
    oldPrice: 99.99,
    rating: 4.4,
    reviewCount: 19574,
    badge: "Amazon's Choice",
    bestFor: "Most Compact Upright",
    image: "/images/products/bissell-cleanview-compact-3508.webp",
    affiliateUrl: "https://amzn.to/4x4teke",
    slugUrl: "/products/bissell-cleanview-compact-3508",
    quickSpecs: [["Model", "3508"], ["Motor", "700W"], ["Weight", "7.5 lbs"], ["Dust Cup", "1 L"], ["Filter", "Disk"]],
    features: ["Removable extension wand", "Crevice tool and dusting brush included", "Compact, lightweight body"],
    pros: ["One of the lightest corded uprights in this guide at 7.5 lbs", "Compact size stores easily in small closets", "Nearly 19,600 ratings at 4.4 stars"],
    cons: ["Smaller 1 L dust cup means more frequent emptying", "Best suited to smaller homes rather than large carpeted spaces"],
    summary: "Bissell's CleanView Compact trims the size and weight of a traditional upright without sacrificing much suction — a smart pick for apartments and smaller homes.",
  },
  {
    serial: 17,
    slug: "nadaly-n16-cordless-vacuum",
    title: "NADALY N16 Cordless Vacuum",
    brand: "NADALY",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 84.99,
    oldPrice: 99.99,
    rating: 4.5,
    reviewCount: 587,
    badge: "Amazon's Choice",
    bestFor: "Best 8-in-1 Value",
    image: "/images/products/nadaly-n16-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/4fXv28M",
    slugUrl: "/products/nadaly-n16-cordless-vacuum",
    quickSpecs: [["Model", "N16"], ["Motor", "600W"], ["Suction Power", "Up to 50 kPa (Max)"], ["Battery Runtime", "Up to 70 min (Min Mode)"], ["Filter", "5-Stage HEPA"]],
    features: ["8-in-1 multi-functional accessory set", "Removable battery", "V-shaped anti-tangle brush", "LED display"],
    pros: ["Long 70-minute runtime on Min mode", "Removable battery for easy replacement", "Strong 4.5-star average across 587 ratings"],
    cons: ["Max mode runtime drops sharply to around 20 minutes", "No official weight listed by the manufacturer"],
    summary: "The NADALY N16 pairs an 8-in-1 accessory set with one of the longer battery runtimes in this guide, backed by nearly 600 solid reviews.",
  },
  {
    serial: 18,
    slug: "zefiro-c11-cordless-vacuum",
    title: "Zefiro C11 Cordless Vacuum",
    brand: "Zefiro",
    type: "Cordless Stick Vacuum",
    category: "cordless-stick-vacuums",
    categoryLabel: "Cordless Stick Vacuums",
    categoryUrl: "/category/cordless-stick-vacuums",
    price: 109.99,
    oldPrice: null,
    rating: 4.1,
    reviewCount: 12,
    badge: null,
    bestFor: "Newest Cordless Listing",
    image: "/images/products/zefiro-c11-cordless-vacuum.webp",
    affiliateUrl: "https://amzn.to/45tUzAo",
    slugUrl: "/products/zefiro-c11-cordless-vacuum",
    quickSpecs: [["Model", "C11"], ["Motor", "600W Brushless"], ["Suction Power", "50 kPa"], ["Battery Runtime", "Up to 55 min"], ["Filter", "HEPA + Multi-Stage Cyclone"]],
    features: ["Multi-stage cyclone filtration", "Wall mount included", "Detachable battery", "LED display", "Includes crevice tool and 2-in-1 brush"],
    pros: ["Multi-stage cyclone filtration is a nice extra at this price", "Detachable battery makes carrying a spare easy", "Full accessory set included"],
    cons: ["Very limited review history so far (12 ratings)", "Lowest rating of the cordless models covered in this guide"],
    summary: "A newer cordless vacuum with cyclone-assisted filtration and a solid feature set — worth a look once it accumulates more reviews to confirm long-term reliability.",
  },
  {
    serial: 19,
    slug: "dreame-l60-ultra-robot-vacuum",
    title: "Dreame L60 Ultra Robot Vacuum & Mop",
    brand: "Dreame",
    type: "Robot Vacuum & Mop",
    category: "robot-vacuums",
    categoryLabel: "Robot Vacuums",
    categoryUrl: "/category/robot-vacuums",
    price: 999.99,
    oldPrice: null,
    rating: 4.2,
    reviewCount: 93,
    badge: "Top Brand",
    bestFor: "Best Robot Vacuum & Mop",
    image: "/images/products/dreame-l60-ultra-robot-vacuum.webp",
    affiliateUrl: "https://amzn.to/4hEb1p0",
    slugUrl: "/products/dreame-l60-ultra-robot-vacuum",
    quickSpecs: [["Model", "L60 Ultra PE"], ["Suction Power", "30,000 Pa"], ["Mop Wash Temp", "212°F (100°C)"], ["Object Recognition", "220+ Types"], ["Dock", "All-in-One PowerDock"]],
    features: ["Auto dust emptying at the dock", "Auto water refill and detergent mixing", "Hot-water mop washing", "Hot-air mop drying", "Faster dock charging"],
    pros: ["Flagship-level suction at 30,000 Pa", "Fully automated dock handles emptying, mopping and drying", "Recognizes 220+ household objects to avoid obstacles"],
    cons: ["Premium price point around $1,000", "Battery runtime isn't disclosed by the manufacturer"],
    summary: "Dreame's L60 Ultra is a genuine flagship robot vacuum and mop, offering near hands-off maintenance thanks to its all-in-one dock — at a premium price to match.",
  },
  {
    serial: 20,
    slug: "eureka-neu181a-upright-vacuum",
    title: "Eureka NEU181A Upright Vacuum",
    brand: "Eureka",
    type: "Corded Upright Vacuum",
    category: "vacuums",
    categoryLabel: "Vacuums",
    categoryUrl: "/category/vacuums",
    price: 89.98,
    oldPrice: 99.99,
    rating: 4.2,
    reviewCount: 8527,
    badge: "Amazon's Choice",
    bestFor: "Best for Pet Hair (Upright)",
    image: "/images/products/eureka-neu181a-upright-vacuum.webp",
    affiliateUrl: "https://amzn.to/3TFD2CJ",
    slugUrl: "/products/eureka-neu181a-upright-vacuum",
    quickSpecs: [["Model", "NEU181A"], ["Suction Power", "13 kPa"], ["Weight", "10 lbs"], ["Dust Cup", "2.6 L"], ["Filter", "Washable Foam"]],
    features: ["Dedicated Pet Turbo Brush", "Includes crevice tool, dusting brush and upholstery tool", "Large 2.6 L bagless dust cup"],
    pros: ["Pet Turbo Brush is purpose-built for fur and dander", "Large 2.6 L dust cup needs less frequent emptying", "Over 8,500 positive ratings"],
    cons: ["Corded only", "At 10 lbs it's heavier than cordless alternatives"],
    summary: "The Eureka NEU181A leans into pet owners specifically with its dedicated Turbo Brush and oversized dust cup — a dependable, affordable upright for fur-covered homes.",
  },
];

/* ---- Utilities ---- */

function formatPrice(price) {
  if (price === null || price === undefined) return null;
  return '$' + price.toFixed(2);
}

function buildStars(rating) {
  const full = Math.round(rating * 2) / 2;
  let html = '<span class="stars" aria-label="' + rating + ' out of 5 stars">';
  for (let i = 1; i <= 5; i++) {
    if (full >= i) html += '<svg viewBox="0 0 20 20" class="star star-full"><path d="M10 1l2.9 6.26L20 8.24l-5 4.86L16.18 20 10 16.27 3.82 20 5 13.1 0 8.24l7.1-.98z"/></svg>';
    else if (full + 0.5 === i) html += '<svg viewBox="0 0 20 20" class="star star-half"><path d="M10 1l2.9 6.26L20 8.24l-5 4.86L16.18 20 10 16.27 3.82 20 5 13.1 0 8.24l7.1-.98z"/></svg>';
    else html += '<svg viewBox="0 0 20 20" class="star star-empty"><path d="M10 1l2.9 6.26L20 8.24l-5 4.86L16.18 20 10 16.27 3.82 20 5 13.1 0 8.24l7.1-.98z"/></svg>';
  }
  html += '</span>';
  return html;
}

function buildProductCard(p) {
  const priceHtml = p.price
    ? '<span class="pc-price">' + formatPrice(p.price) + '</span>' +
      (p.oldPrice ? '<span class="pc-price-old">' + formatPrice(p.oldPrice) + '</span>' : '')
    : '<span class="pc-price pc-price-cta">Check Price</span>';
  const badgeHtml = p.badge ? '<span class="pc-badge">' + p.badge + '</span>' : '';
  const reviewCountHtml = p.reviewCount ? '<span class="pc-rating-count">(' + p.reviewCount.toLocaleString() + ')</span>' : '';
  return `
  <article class="product-card">
    ${badgeHtml}
    <a href="${p.slugUrl}" class="product-card-img">
      <img src="${p.image}" alt="${p.title}" loading="lazy"
           onerror="this.onerror=null;this.src='https://placehold.co/500x400/f2f2f2/999999?text=Photo+Coming+Soon';">
    </a>
    <div class="product-card-body">
      <span class="pc-cat">${p.categoryLabel}</span>
      <a href="${p.slugUrl}"><h3 class="pc-title">${p.title}</h3></a>
      <div class="pc-rating-row">${buildStars(p.rating)}${reviewCountHtml}</div>
      <div class="pc-price-row">${priceHtml}</div>
      <div class="pc-actions">
        <a href="${p.slugUrl}" class="pc-btn pc-btn-outline">Read Review</a>
        <a href="${p.affiliateUrl}" class="pc-btn pc-btn-solid" target="_blank" rel="nofollow sponsored noopener">Check Price</a>
      </div>
    </div>
  </article>`;
}

function renderProductGrid(containerId, products) {
  const el = document.getElementById(containerId);
  if (!el) return;
  el.innerHTML = products.map(buildProductCard).join('');
}

function getProductBySlug(slug) {
  return PRODUCT_REGISTRY.find(p => p.slug === slug) || null;
}
